baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-book"

# Book configuration
[params]
  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  BookToC = true

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be logo.png
  # BookLogo = 'logo.png'

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  BookSection = '*'

  # (Optional, default false) Enable search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  BookSearch = true

  # (Optional, default true) Enables comments template on pages
  # By default partals/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  BookComments = true

  # (Optional, default false) Enables siblings menu for next/prev page navigation
  BookSiblingMenu = true

# 添加主菜单配置

[[menu.main]]
  name = "Hugo"
  url = "/hugo/"
  weight = 1

[[menu.main]]
  name = "RD"
  url = "/rd/"
  weight = 2

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1
  endLevel = 3